name = "unspec-bit/mintforge"
version = "0.0.0"
compiler = "v1.1.17"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for unspec-bit/mintforge"

[repository]
user = "unspec-bit"
project = "mintforge"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"

[config]
